rsksmart/rwallet

- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/zh.json
- src/components/common/passcode/passcode.modal.verify.js
vscode plugin:
Code Spell Checker
> Fix typos. #fix 25, fix #26, fix #28

- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/zh.json
- src/pages/mine/index.js
> Pluralize wallets. fix #24

- config.js
- src/common/translations/en.json
- src/common/translations/es.json
> Homogeneous case. fix #37, fix #45

- src/pages/wallet/dashboard/wallet.carousel.page.wallet.js
> Expand the clickable area of dashboard buttons 

- src/pages/wallet/swap/swap.js
> Remove unused element of coinswitch page

- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/zh.json
- src/pages/mine/reset.passcode.success.js
- src/pages/mine/two.factor.auth.js
> Add "Set Passcode" text. fix #29

- src/pages/wallet/receive.js
- src/pages/wallet/recovery.phrase.js
> Expand the hot zone of the copy button. fix #57

- src/redux/app/saga.js
> Add notification of sent transaction

- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/zh.json
- src/pages/wallet/transfer.js
> Add balance in transfer page. fix #89, fix #39

- src/assets/styles/style.js
- src/components/headers/back.button.js
- src/components/headers/header.history.js
- src/components/headers/header.operation.js
- src/components/headers/header.swap.js
> Expand the hot zone of back button. fix #35

- src/pages/wallet/dashboard/wallet.carousel.page.wallet.js
> Modify amount position. fix #41

- src/common/common.js
- src/common/wallet/wallet.js
- src/pages/wallet/add.token.js
**List**
**Add Tokens**
**Key Setting**
> Unify order of tokens. fix #42

- src/common/wallet/walletManager.js
- src/pages/wallet/dashboard/list.js
> Modify order of wallets

- src/pages/wallet/history.js
- src/pages/wallet/transaction.js
> Add refresh control in transaction page. fix #40

- src/common/common.js
- src/pages/wallet/history.js
- src/pages/wallet/select.wallet.js
- src/pages/wallet/transfer.js
**History**
**Transfer**
**Select Asset**
> Fix the name and fiat value of testnet token. fix #120

- src/common/parseDataUtil.js
> Fix parse prices and block height

- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/zh.json
- src/pages/wallet/add.token.js
> Add translation of custom token

- src/pages/wallet/recovery.js
> Fix style of path text input. fix #136

- src/common/common.js
- src/common/wallet/btccoin.js
- src/common/wallet/rbtccoin.js
- src/common/wallet/wallet.js
- src/pages/wallet/add.custom.token.confirm.js
- src/pages/wallet/dashboard/list.js
- src/pages/wallet/history.js
- src/pages/wallet/swap/swap.js
- src/pages/wallet/swap/swap.selection.js
- src/pages/wallet/transaction.js
- src/pages/wallet/transfer.js
> Fix symbol decimal places

- package-lock.json
- package.json
- src/common/common.js
- src/common/transaction/rbtccoin.js
- src/common/wallet/rbtccoin.js
- src/pages/wallet/add.custom.token.js
- src/pages/wallet/scan.js
- src/pages/wallet/transfer.js
Fix compile error on android:
```
> Task :rn-secure-storage:compileDebugJavaWithJavac FAILED
/Users/star/devlab/rwallet/node_modules/rn-secure-storage/android/src/main/java/com/taluttasgiran/rnsecurestorage/Constants.java:2: 错误: 需要<标识符>
public class Constants {a
```
> Fix compile error

- src/navigation/components/bottom.tab.js
- src/navigation/tab.primary.js
> Fix tabbar i18n. fix #58

- src/pages/wallet/transfer.js
> Replace comma as dot. fix #93

- android/app/build.gradle
- android/app/src/main/java/com/rsk/rwallet/reactnative/MainApplication.java
- android/settings.gradle
- ios/rwallet.xcodeproj/project.pbxproj
- package-lock.json
- package.json
- src/common/common.js
- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/zh.json
- src/components/common/modal/touchSensorModal.js
- src/components/common/passcode/passcode.modal.base.js
- src/components/common/passcode/passcode.modals.js
- src/navigation/component.js
- src/pages/mine/two.factor.auth.js
- src/pages/wallet/dashboard/dashboard.js
- src/pages/wallet/transfer.js
> Passcode blur background. fix #147

- src/common/settings.js
- src/common/wallet/walletManager.js
1. Fix the wallet name's regex rule
2. Fix the key name's regex rule
3. Fix the ESLint error: Missing file extension "json" for "./constants"
> fixed rename issue. fix #155

- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/zh.json
- src/pages/wallet/dashboard/wallet.carousel.page.wallet.js
- src/pages/wallet/recovery.js
1. fix issue #166 
2. fix issue #169
> Change select coin popup title,  expand "Add asset" button area. fix #166, fix #169

- src/common/common.js
- src/pages/base/base.page.simple.js
- src/pages/mine/index.js
- src/pages/start/terms.js
- src/pages/wallet/swap/swap.selection.js
**1. Fix spaces in create and import wallet**
**2. Fix loading when creating wallet**
**3. Fix size of support icons**
iOS
android
**4. Fix Fingerprint type**
> Fix RIF Wallet problems. fix #164

- src/common/translations/en.json
I think makes more sense Asset instead of Wallet in this case.
> Update en.json - Asset instead of Wallet

- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/zh.json
1. change "Wallet" to "Asset"
2. change "Currency" to "Asset"
> Fix translate issue

- ios/en.lproj/InfoPlist.strings
- ios/es.lproj/InfoPlist.strings
- ios/pt-PT.lproj/InfoPlist.strings
- ios/rwallet.xcodeproj/project.pbxproj
- ios/rwallet/Base.lproj/LaunchScreen.xib
- ios/rwallet/Info.plist
- ios/zh-Hans.lproj/InfoPlist.strings
> Notice message of permissions. fix #165

- src/common/translations/en.json
- src/common/translations/es.json
> Modify password to passcode

- src/common/errors.js
- src/common/notification.controller.js
- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/zh.json
- src/pages/wallet/add.custom.token.js
- src/pages/wallet/swap/swap.js
- src/pages/wallet/transfer.js
> Handle error with error code. fix #148, fix #201

- src/common/translations/en.json
- src/common/translations/es.json
> Fix fee question

- App.js
> Set status bar background to theme color. fix #163

- src/pages/wallet/swap/swap.js
> set swap input keyboard type to numeric. fix 216

- src/pages/wallet/receive.js
> Fix crash about sharing. fix #229

- src/components/rns/create.rns.confirmation.js
**1 wallet** 
**Many wallets**
> Adjust height of confirm modal. fix #226

- src/pages/wallet/receive.js
**HUAWEI nova youth**
**iPhone 8**
> Fix the style of copy button in receive page. fix #228

- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/ptBR
- src/common/translations/zh.json
- src/pages/wallet/swap/swap.selection.js
> Prevent Balance null in swap. fix #203

- ios/rwallet.xcodeproj/project.pbxproj
- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/ptBR
- src/common/translations/zh.json
- src/pages/wallet/dashboard/wallet.carousel.js
**Name Button**
**Pending Button**
**Done Button**
**Receive page**
**Add Wallet Button**
> Add translations for RNS

- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/ptBR
- src/common/translations/zh.json
- src/pages/wallet/add.token.js
- src/pages/wallet/dashboard/wallet.carousel.page.wallet.js
- src/pages/wallet/swap/swap.js
- src/pages/wallet/transfer.radio.group.js
**Wallet List**
**Add Token**
**Swap**
**Wallet Settings**
**Transfer**
> Fix long translations. fix #190, fix #204

- android/app/build.gradle
- android/app/src/main/java/com/rsk/rwallet/reactnative/MainApplication.java
- android/settings.gradle
- ios/rwallet.xcodeproj/project.pbxproj
- package-lock.json
- package.json
- src/common/fcmHelper.js
修复getToken阻塞app的问题
fork了react-native-firebase, 修改了react-native-firebase中getToken函数的代码，并发布到npm上。
npm
https://www.npmjs.com/package/@imstar15/react-native-firebase
github commit
https://github.com/imstar15/react-native-firebase/commit/9147c737454f4402acd3765c5b62df9f64df0121
> Fix getToken blocking. fix #248

- package-lock.json
- package.json
Upgrade firebase to fix iOS compile error.
> Upgrade firebase version

- src/pages/wallet/select.currency.js
> Modify import button in select currency page. fix #258

- src/components/common/carousel/ads.carousel.js
> modify ads carousel margin style

- src/components/common/modal/wallet.selection.modal.js
- src/components/common/progress.webview/lib/webview.js
- src/pages/dapp/browser.js
- src/pages/dapp/index.js
Override some web3 methods to adapt ROC dapp and MOC dapp.
> Adapt roc moc

- fastlane/Fastfile
- fastlane/Matchfile
**fastlane/.env**
```
APP_IDENTIFIER="com.rsk.rwallet.reactnative"
USERNAME=""
FASTLANE_PASSWORD=""
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=""
TEAM_ID=""
FASTLANE_ITC_TEAM_NAME=""
GIT_URL="git@xxx.com:xxxx/xxxxx.git"
MATCH_PASSWORD=""
ANDROID_SIGN_FILE="android/app/keystores/release.rwallet.jks"
ANDROID_SIGN_PASSWORD=""
ANDROID_SIGN_KEY_ALIAS="key0"
ANDROID_SIGN_KEY_PASSWORD=""
SLACK_URL=""
```
> Fastlane build ios

- config.js
- src/common/common.js
- src/common/constants.json
- src/common/i18n.js
- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/ptBR.json
- src/common/translations/zh.json
- src/components/common/modal/touchSensorModal.js
- src/navigation/component.js
- src/navigation/container.js
- src/pages/dapp/browser.js
- src/pages/dapp/index.js
- src/pages/dapp/list.js
- src/pages/mine/two.factor.auth.js
- src/redux/app/actions.js
- src/redux/app/reducer.js
- src/redux/app/saga.js
This PR #154 is not available because the branch seems to have been deleted.
1. Add Face ID recognition
2. Add Brazilian Portuguese Option
> Add facial recognition when the device allows. Add Brazilian Language. fix #60, fix #268

- src/pages/dapp/index.js
- src/pages/dapp/list.js
> show dapp warning when first into dapp

- src/pages/wallet/swap/swap.selection.js
Set bounces to false so FlatList will not slide out of the view
> set bounces to false. fix #279

- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/pt.json
- src/common/translations/ptBR.json
- src/common/translations/zh.json
> Fix asset issue. Fix #43

- src/assets/styles/color.ts
- src/components/common/image/image.js
- src/pages/dapp/index.js
> set image placeholder bg color

- config.js
- src/pages/mine/index.js
- src/pages/start/terms.js
Chinese:
Portuguese and Brazilian Portuguese:
Spanish:
> set terms of use multiple language. Fix #301

- src/pages/wallet/swap/swap.selection.js
> switch swap then set swap source. Fix #303

- src/common/common.js
> set rifpro price = rif price, rdoc price = doc price. Fix #297

- src/common/translations/ptBR.json
> Fix ptbr of no enough balance. fix #342

- src/assets/styles/header.browser.styles.js
- src/components/common/misc/loc.js
- src/components/common/webview.modal.js
- src/components/headers/header.browser.js
- src/components/headers/header.dappbrowser.js
- src/pages/dapp/browser.js
- src/pages/mine/index.js
> Enhance web modal. fix #299

- src/pages/wallet/history.js
> no more data if list data is empty. Fix #347

- src/pages/wallet/transfer.js
> Enlarge the touchable area of qrcode. fix #355

- config.js
- src/common/common.js
- src/pages/dapp/browser.js
- src/pages/dapp/index.js
- src/pages/dapp/list.js
添加了默认的Dapp Logo，显示domain作为dapp的url链接
webview不能够判断url是否是有效的，所以这一块没有做。
check "http/https"这一块，之前有做过自动补全"http"，跟现在的check不一样，我这边选择了自动补全的效果，因为用户输入不会每次都先打"https://"或者"http://"。
> Amazingbeerbelly add default dapp icon. Fix #352

- src/pages/wallet/rns/create.js
> Fix the clickable area of trash button in swap page. fix #398

- ios/rwallet.xcodeproj/project.pbxproj
- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/ja.json
- src/common/translations/ko.json
- src/common/translations/pt-BR.json
- src/common/translations/pt.json
- src/common/translations/ru.json
- src/common/translations/zh.json
- src/pages/wallet/swap/swap.js
> Fix Exchanging and Receiving translation in swap page. fix #390

- android/app/build.gradle
- android/build.gradle
Update compileSdkVersion and buildToolsVersion to 29.0 to make Pixel 4 Biometric work
> Update version to Pixel 4 biometric

- src/pages/wallet/history.js
> Fix short date. fix #414

- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/ja.json
- src/common/translations/ko.json
- src/common/translations/pt-BR.json
- src/common/translations/pt.json
- src/common/translations/ru.json
- src/common/translations/zh.json
I modified the title.
@bitcoinuser
> Modify the title of select wallet assets

- src/components/wallet/coin.type.list.item.js
- src/pages/wallet/select.currency.js
> Deselecting all currencies. fix #379

- src/components/common/confirmation/confirmation.panel.js
- src/components/common/modal/address.selection.modal.js
- src/components/common/modal/selection.modal.js
- src/components/common/modal/wallet.selection.modal.js
- src/components/common/notification/alert.js
- src/components/rns/create.rns.confirmation.js
- src/components/rns/subdomain.unavailable.notification.js
- src/components/update/update.modal.js
- src/navigation/component.js
- src/pages/start/webview.modal.js
在打开rwallet进入密码验证的时候，如果点击安卓物理返回键，则退出app。在Dapp Browser的Modal显示情况下，点击安卓物理返回键，则关闭Modal。
> Close modal when click android back button. Fix #356, Fix #392.

- src/components/common/progress.webview/lib/webview.js
- src/pages/dapp/browser.js
> Fixed dapp browser MOC open issue. Fix #422. Fix #419

- src/pages/mine/key.settings.js
> Hide the back up button of read-only wallet. fix #479

- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/ja.json
- src/common/translations/ko.json
- src/common/translations/pt-BR.json
- src/common/translations/pt.json
- src/common/translations/ru.json
- src/common/translations/zh.json
- src/pages/wallet/scan.js
- src/pages/wallet/select.wallet.js
- src/pages/wallet/transfer.js
- src/pages/wallet/wallet.connect/index.js
在做walllet connect的时候，改了扫一扫转账的流程，昨天测试了下，发现了一些问题，然后改了。
> fix scan and transfer logic issue

- src/pages/dapp/browser.js
Override window.ethereum.request to adapt "Crypto Quiz" dapp.
> Dapp browser override window.ethereum request method.

- src/components/common/switch/switch.row.js
> Add switch row component

- src/components/wallet/wallet.type.list.js
> Fix font style in add wallet page. fix #537

- src/common/constants.js
- src/common/parse.js
- src/common/wallet/cointype.js
- src/common/wallet/rbtccoin.js
- src/pages/wallet/dashboard/wallet.carousel.page.wallet.js
- src/pages/wallet/history.js
- src/redux/wallet/actions.js
- src/redux/wallet/saga.js
> Pull down to refresh token balance. fix #525, fix #515

- src/pages/dapp/browser.js
- src/pages/wallet/wallet.connect/index.js
- src/pages/wallet/wallet.connect/modal/transaction.js
白屏的原因是因为，dapp传入一个value值为"0x2386f26fc10000"，然后我在转成Number的时候，用了Rsk3.utils.hexToNumber这个方法，然后就报错了。现在用了BigNumber就可以了。
> fix wc white screen issue.

- src/common/constants.js
- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/ja.json
- src/common/translations/ko.json
- src/common/translations/pt-BR.json
- src/common/translations/pt.json
- src/common/translations/ru.json
- src/common/translations/zh.json
- src/pages/wallet/wallet.connect/index.js
> Wallet Connect Add connect timeout alert. Fix #559

- src/pages/dapp/browser.js
- src/pages/wallet/wallet.connect/index.js
- src/pages/wallet/wallet.connect/modal/transaction.js
> Add to address link. fix #606

- src/pages/dapp/browser.js
> Fix sovryn cannot connect wallet issue.

- src/common/transaction/index.js
- src/common/transaction/rbtccoin.js
- src/pages/wallet/swap/swap.js
以下是通过sendSignedTransaction接口传给服务端的数据。
```
{
"name": "Rootstock",
"hash": "0xf8aa819784070f23668301979894e700691da7b9851f2f35f8b8182c69c53ccad9db80b844a9059cbb00000000000000000000000098715b70fecee1d7a58afd013110d8220bc63c55000000000000000000000000000000000000000000000001158e460913d000005fa02f438bfa2554dbb3e436e158e56664c06965f6f2a2030464faa9784fa190c7baa005134ef7a7664f08a0a92ee33a20d642b9716bef347a2ad69a82594cc57e08cb",
"type": "Mainnet",
"raw": {
"from": "0xbb18df33a915a2cff0caf0edd59bd3e7606d0a83",
"nonce": "0x97",
"chainId": 30,
"gas": "0x19798",
"gasPrice": "0x70f2366",
"value": "0x0",
"to": "0xe700691da7b9851f2f35f8b8182c69c53ccad9db",
"data": "0xa9059cbb00000000000000000000000098715b70fecee1d7a58afd013110d8220bc63c55000000000000000000000000000000000000000000000001158e460913d00000"
}, …
```
> Post raw transaction to server

- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/ja.json
- src/common/translations/ko.json
- src/common/translations/pt-BR.json
- src/common/translations/pt.json
- src/common/translations/ru.json
- src/common/translations/zh.json
- src/components/common/modal/wallet.selection.modal.js
- src/pages/wallet/add.custom.token.js
- src/pages/wallet/readonly/add.js
- src/pages/wallet/readonly/confirm.js
- src/pages/wallet/rns/create.js
- src/pages/wallet/select.currency.js
> Modify Mainnet,Testnet translation. #554

- src/components/common/misc/type.tag.js
- src/pages/wallet/history.js
- src/pages/wallet/rns/create.js
> Add type tag after balance. fix #579

- __test__/common.test.js
- jest.config.js
- src/common/common.js
getSymbolName
toChecksumAddress
getServerUrl
ellipsisAddress
uppercaseFirstLetter
> Test functions(getSymbolName, toChecksumAddress…) in common.js

- .eslintrc.js
- android/app/build.gradle
- ios/rwallet.xcodeproj/project.pbxproj
- package-lock.json
- package.json
- Adds `package-lock.json` file
- bumps version to `1.4.0`
- edits linter rule for functions complexity to be a warning
> chore: stabilizes develop branch

- src/common/translations/es.json
Fixes two spelling errors in Spanish text. Please double-check the corrections as I am not a Spanish speaker.
> Fix two spelling mistakes in Spanish text.

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- ios/rwallet.xcodeproj/project.pbxproj
- package-lock.json
- package.json
> chore: bumps version to 1.4.1

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- ios/rwallet.xcodeproj/project.pbxproj
- package-lock.json
- package.json
We create a separate branch for adding only the fix in #664 to the 1.4.1 version.
After releasing and tagging, we should merge the branch back to master to reflect 1.4.2 in master.
> chore: update version 1.4.2

- docs/CONTRIBUTING.md
Goal: Be compliant with the github Community standards.
> chore: Create CONTRIBUTING.md

- docs/PULL_REQUEST_TEMPLATE/pull_request_template.md
Goal: Be compliant with the github Community standards.
> chore: Create pull_request_template.md

- src/pages/wallet/transfer.js
Fixed transfer when BTC address where Base58 (1.../3...).
Base58 is case SENSITIVE alphanumeric, and we where lowercasing before building the transaction making it fail.
Additionally, report error log to server has been added to the transfer confirmation.
It fixes #685 
Made a BTC transfer. Also you can make a tBTC tranfer to this address (faucet): `mkHS9ne12qx9pS9VojpwU5xtRd4T7X7ZUt` to reproduce the error.
> fix: BTC transfer to Legacy address

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- ios/rwallet.xcodeproj/project.pbxproj
- package-lock.json
- package.json
> chore:bump to version 1.4.4

- src/pages/wallet/wallet.connect/index.js
This should fix transactions when using wallet connect on sovryin.
I connected to sovryn a swapped RTBC for SOV
> fix: convert address to lower case for wallet connect transactions

- __test__/transactionServices.test.js
- src/pages/wallet/transfer.js
- src/services/transactionServices.js
Extract tx broadcast code from component and add unit test (pending)
**The following cases will be in a separate PR:**
Segwit RBTC to Segwit RBTC (Partial funds))
USDT to USDT (Partial funds))
Legacy BTC to Legacy BTC (All funds)
USDT to USDT (All funds)
Decouple logic from component to make it easier to test
Yes, locally
- [ x] My code follows the code style of this project.
* **Other information**:
* **SCREENSHOTS**:
> refactor: extract tx broadcast from component and add unit tests

- src/common/translations/en.json
- src/common/translations/es.json
This error usually happens when connecting to Sovryn. It can be fixed clearing browsing data.
> Improve timeout message

- src/components/common/passcode/passcode.modal.verify.js
- src/services/serverServices.js
> Move timestamp code

- android/app/src/main/res/values/styles.xml
* **Other information**:
* **SCREENSHOTS**:
> fix: dark mode styles

- src/components/common/misc/loader.js
> fix: make spinner black
