rsksmart/rwallet

- src/navigation/component.js
- src/navigation/container.js
- src/redux/wallet/actions.js
- src/redux/wallet/reducer.js
- src/redux/wallet/saga.js
The previous transaction list was incorrect, and the most recent one came to the tail of list. This PR was modified to fix this problem.
The data returned by fetch is sorted to the end of the list in order, and the data updated by subscription is inserted into the head of the list.
> Fix transactions order

- src/common/common.js
- src/common/parseDataUtil.js
- src/redux/wallet/saga.js
修复以下情况下的bug:
1. 用户进入列表，页面会自动获取前10条信息。
2. 用户发送一笔交易，此时刚好live query断线，一段时间重连成功后，那笔交易未能通过live query更新到列表中。
3. 当用户再次进入列表，页面再次自动获取前10条信息（包含刚刚发送出去的那条交易），按之前的规则，新交易会被push到列表尾部。
解决方法：
每次fetch或update transactions时，需要对transactions按receivedAt进行排序。因为之前的数组已经是有序的，则按快速排序的方法，算法复杂度会是O(n)，n为token.transactions.length（已在列表中元素数量），且只是更新transactions时调用，是可接受的。
> Fix the order of transactions

- src/common/parse.js
- src/redux/wallet/saga.js
Fix issue #171: Transaction History ordering is not consistent
1. First send 1 RIF, then send 2 RIF
2. 1 RIF transaction has been confirmed, and 2 RIF transaction is still sending
3. 2 RIF transaction has been confirmed.
> Fix transaction ordering issue. Fix #171

- android/app/build.gradle
- android/app/src/main/java/com/rsk/rwallet/reactnative/MainApplication.java
- android/settings.gradle
- package.json
- src/components/common/webview.modal.js
- src/pages/mine/index.js
- src/pages/start/terms.js
实际上react-native-webview使用的是androidx支持库，我们使用的react-native 0.59.10不支持androidx，但是使用`jetifier -r`可以将androidx替换为android.support.v4的库。
如果编译时出现
```
/Users/star/devlab/rwallet/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:14: 错误: 找不到符号
import androidx.annotation.RequiresApi;
^
符号:   类 RequiresApi
位置: 程序包 androidx.annotation
/Users/star/devlab/rwallet/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:15: 错误: 程序包androidx.core.content不存在
import androidx.core.content.ContextCompat;
```
我们可以运行`npm run postinstall`去解决。
> Fix webview

- src/pages/wallet/transaction.js
之前这个界面的余额显示不正确，显示为0。
v1.1.1测试时发现，并修复了。
> Fix balance in transaction detail

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/rsk/rwallet/reactnative/MainApplication.java
- android/gradle.properties
- package-lock.json
- package.json
- src/common/common.js
- src/common/constants.json
- src/common/translations/zh.json
- src/components/common/modal/touchSensorModal.js
因为旧版本react-native-device-info:2.3.2含UIWebView会影响到iOS提交，新版本5.6.3必须使用AndroidX。
为了支持AndroidX，做了如下配置和修改。
1. 通过jetifier将android.support.v4转成AndroidX
1. 配置gradle.properties使用AndroidX
```
android.useAndroidX=true
android.enableJetifier=true
```
3. 修改react-native-fingerprint-scanner到6.0.0版本，支持AndroidX 
react-native-fingerprint-scanner:6.0.0与旧版本不同的是会弹出这个界面进行指纹验证。
> Add AndroidX support

- src/components/common/modal/wallet.selection.modal.js
我把字体放大了，图片是在模拟器上面跑的效果。具体效果可能需要Chris真机上面跑下看看，因为我这边的真机没有这个ui问题。
> change token font size. Fix #326

- src/pages/dapp/browser.js
是nonce造成的bug。当我第一次发送交易成功之后，马上发送第二次交易，这时候从链上取到的nonce，还是上一笔交易的nonce（可能是因为上一笔交易还没有上链），所以造成交易失败。
本地发送的交易，需要把nonce保存到一个变量，当本地的nonce大于链上取回的nonce的时候，就优先使用本地的nonce值。
> fix rif faucet issue. Fix #353

- src/pages/dapp/browser.js
修复RNS Dapp中，window.ethereum.send和window.ethereum.send这两个方法有时候是undefined的问题，会造成RNS在注册domain的时候，会一直在转圈，获取不到结果，实际上是已经完成的问题。
> fix rns get result issue

- config.js
When the custom token decimal is 3, "0.00027" will show "0".
Set the custom token decimals to 6 could fix this issue.
> change custom token decimals from 3 to 6. Fix #498

- android/app/build.gradle
- android/app/src/main/java/com/rsk/rwallet/reactnative/MainApplication.java
- android/settings.gradle
- ios/rwallet.xcodeproj/project.pbxproj
- package-lock.json
- package.json
- src/pages/wallet/receive.js
经测试，目前无法支持同时分享图片+文字到一些APP上（如微信），只能分享图片、文字其中一种内容。
我看了bitpay，它是分享钱包地址文本。
因此我去掉截图和分享图片的功能，只分享钱包地址文本。
注：目前iOS平台下，不支持分享到微信。（bitpay同样也不支持）
iOS环境，bitpay分享到微信的错误提示如下，同样也会出现在rwallet。
如果需要完全支持微信分享，需要集成微信SDK。
2020.10.12更新
修改成分享截图，iOS下微信可分享截图。
> Fix share issue. fix #512

- src/pages/dapp/browser.js
Assign the web3 provider according to the dapp name to fix MoC cannot open issue
> Fix android dapp browser cannot open MoC issue

- README.md
- package.json
- postinstall/blacklist.js
Two small updates for running: 
- Adds nodeify to the postinstall process which happens after installing. A developer can now run `npm i` and then `npm run android` to start the app.
- Add a copy function to the metro-config blacklist file. This solves an known issue in Windows. The fixed file was published into the `/postinstall/` folder, however, only lines 14-19 have been changed. [See this blog post for more information about the error.](https://medium.com/@wasiquehaider/metro-bundler-closing-after-running-react-native-run-android-65c6db4a3335).
> Fix install script and add hotfix file for windows.

- src/navigation/components/bottom.tab.js
- src/navigation/tab.primary.js
- src/pages/wallet/dashboard/wallet.carousel.page.wallet.js
Removes access to the swap screen, which is accessible from two places:
1. The main tab row at the bottom. Where the new number of items is 3 and their widths are calculated based on the screen width.
2. From the Wallet "My Assets" summary box, the swap button. CSS alignment needed to be updated.
**Screen shot from Galaxy A20e**
This does not remove the swap UI or its interaction. The UI can be used in the future with a new swap provider.
Pixel 3 (emulator) and Samsung Galaxy A20e (real)
- **Tab button row:** click through the items to make sure the hitbox was correct and the spotlight (i.e. the blue line) was the correct width and placement.
- **Summary Card** tested to make sure send and receive buttons still work, and have enough spacing between them for fat fingers.
While this does …
> Removes the buttons to get to the swap screen. 

- __test__/transaction.test.js
- src/common/transaction/rbtccoin.js
- src/pages/wallet/transfer.js
By @jessgusclark 
Checksums are important for users to understand if they are sending funds/tokens to the correct network. However, they are not needed for computers.
As such, this change leaves intact the warning to the user that the recipient address is not checksummed for this network. After the user clicks to confirm, and that they understand, there is no need to check the checksum anymore. Therefore, at this step of the process, the address can be converted to lowercase and passed on.
---
Lowercases addresses that are not shown to users.
Closes #561
Closes #558
> fix: lowercases addresses before making operations

- src/common/transaction/btccoin.js
- src/common/transaction/index.js
- src/common/wallet/btccoin.js
Gets the `publicKey` from the `privateKey` on `transaction/btccoin.js`.
`publicKey` was missing and so was throwing an error with the message `"Not enough data"` when wanted to send btc transactions.
> fix: fixes btc txs by providing publicKey

- src/pages/start/terms.js
Allows the user to click the back button from the Terms of Use page when initially launching the app.
- The property `onBackButtonPress()` is an internal function of the WebViewModal component. Instead, use the `onCloseButtonPress()` method that is accessible from the props.
- The internal `onBack...` method checks if the web component can go back, and if so, it takes the user back a page in the web browser. Perhaps they clicked on the privacy policy and now want to go back to the TOS page.
- When the user clicks on the 'x' button, it fires the `onClose...` function, which is the expected behavior.
- Uninstall the app to clear the RN storage
- Install, on the tos page, click to "View complete Terms of Use"
- Click Close
- Click "View..." again,
- Click on a link, such as "Privacy Policy", …
> Fix issue to return to setup after viewing terms of use

- src/common/parse.js
- src/redux/app/actions.js
- src/redux/app/reducer.js
- src/redux/app/saga.js
Removes `createRawTransaction` call to the server. That request is not being used anymore in the app.
> refactor: removes unused call to createRawTransaction endpoint

- package-lock.json
- package.json
- src/common/parse.js
- src/pages/wallet/readonly/add.js
- src/pages/wallet/rns/domainToAddress.js
- src/pages/wallet/transfer.js
Check .rsk domains by using the [RNS Resolver JS](https://github.com/rsksmart/rns-resolver.js) package, rather than connecting to the server to get the resolved address. Works with RSK address on Testnet and Mainnet and BTC on Mainnet.
**Note**: with the RNS Manager, there is no way to set the BTC address to a testnet address [See this issue](https://github.com/rnsdomains/rns-manager-react/issues/401). Therefore, when sending tBTC, it will always throw the error "Address is not valid". BTC on Mainnet works correct.
- Previous resolver would only allow `*.wallet.rsk` addresses. This fix allows any .rsk address.
- Single sources search for address using `domainToAddress` file. 
- When an address is not found, or the package throws an error, show 'can't find domain' message to user rather …
> Fix RNS domain resolution

- src/navigation/component.js
This PR removes the hardware back button functionality to close the Fingerprint and Passcode modal. 
With other parts of the app, such as the Dapp Browser, disabling the back button can be done with the [BackHandler](https://reactnative.dev/docs/backhandler). However, since this a modal, and is visible, `BackHandler` events will not fire. See the first warning in the BackHandler link above. As such, the [onRequestClose](https://reactnative.dev/docs/modal#onrequestclose) event will fire when the Back Button is pressed.
In the previous code, if the user clicked the back button, it fired the `onRequestClose` event, which in the end, would hide the modal's contents, closing the modal. See removed lines 127 and 132.
The biometrics component already had the functionality to fallback to a …
> Disable Back button for biometrics and passcode modal.

- src/common/translations/es.json
I did a search of the code to make sure that this string isn't used anywhere else. It is only used once, on the verify screen below confirm: https://github.com/rsksmart/rwallet/blob/master/src/pages/wallet/verify.phrase.js#L323
> Change claro to limpiar.

- src/common/translations/es.json
Add curly brackets to count in Spanish string. Checked other languages and all of them have five instances of `{{count}}`.
> Fix Spanish language text

- src/common/common.js
- src/components/common/modal/wallet.selection.modal.js
- src/pages/dapp/browser.js
- src/pages/wallet/wallet.connect/modal/message.js
Improvements to the rWallet Dapp Browser.
- Removes internal checksums. Case: dapp submits a lowercase address and wallet was converting to checksummed version for some reason. 
- Allows signing of strings, not just hex values.
- Show wallet name above address when choosing which account to use.
- Adds isRWallet flag to the web3 provider. Resolves #643 
- Adds scrollable view when signing messages if the message is too large. Will be used in the future, when creating presentations from the RIF Id Manager. Resolves #635
- Fixes response type when sending `provider.request` from a dapp.
Let's talk about [this code](https://github.com/rsksmart/rwallet/pull/653/files#diff-0880122ef7a357df624e92aeeb17f19fca9e62f7699f82fe01140885e9b6fb8eR339-R344):
```
window.ethereum.request = (payload) =>
new …
```
> Improve dapp browser

- shim.js
We were having error when building for Android with the message: `Can't find variable: BigInt`
@jessgusclark found that we were missing some config in `shim.js` according to the doc in https://www.npmjs.com/package/@rsksmart/rns-resolver.js , under the section 'Usage in React Native'.
We tested locally, and it worked.
> fix: android bigint issue

- src/assets/styles/color.js
- src/pages/mine/index.js
- In the section "Me -> Community" we have outdated community Gitter, so we should add Slack and remove previous Gitter link.
- Changed mail from app@iovlabs.org to rwallet-dev@iovlabs.org.
Also fix some lint issue regarding PropTypes.
> chore: add slack to community

- src/common/storage.js
- src/common/translations/en.json
- src/common/translations/es.json
- src/common/translations/ja.json
- src/common/translations/ko.json
- src/common/translations/pt-BR.json
- src/common/translations/pt.json
- src/common/translations/ru.json
- src/common/translations/zh.json
- src/components/common/passcode/passcode.modal.base.js
- src/components/common/passcode/passcode.modal.verify.js
- src/components/common/passcode/wrongPasscodeUtils.js
- Avoids users to enter passcodes on too many consecutive wrong attempts
- Adds countdown timer to show when users can retry
- Handles steps for retries dynamically
- Persists wrong attempts count and last attempt timestamp between sessions
- Adds loader while checking if user can already retry
- I just got the translation from Google so not sure if they are the most accurate
- It might be better to map props to state and read them on `componentWillReceiveProps` instead of using `baseModal.resetModal(...)`, but that would require a refactor of the base modal dependencies as well (reset passcode, create new passcode, wrong passcode
- Wrong retries count and timer should persist between sessions (ie: closing and re-opening the app)
- With the provided configuration, the app should behave …
> feat: locks passcode screen on too many wrong consecutive attempts

- src/common/error/report.error.js
- src/common/parse.js
- src/pages/wallet/add.custom.token.confirm.js
- src/pages/wallet/add.custom.token.js
- src/pages/wallet/rns/create.js
- src/pages/wallet/transfer.js
- src/pages/wallet/wallet.connect/index.js
- src/redux/price/saga.js
- src/redux/wallet/saga.js
Most of the errors this will be used with will be called from code files, however, some do occur within components. Until the code is separated, this module should be able to be called from anywhere.
It allows the developer to send optional parameters `developerComment` and `additionalInfo` to provide information that may not be in the error.
- `developerComment` could be the location of the error, or part of the process, or something where the developer could search for the string in the code and find the location quickly.
- `additionalInfo` could be the address of the user, or the subdomain they are trying to register, or any other information that would be helpful.
In this initial batch of errors, they are triggered where the getDefaultError() is found. This is the error that shows the …
> Report errors to the server when the DefaultError is thrown

- README.md
- Android SKD 10 (Api level 29)
- xCode v11.x required. Version 12 doesn't work
Error when using SDK 11 ->
Error when using xCode 12.x ->
> chore: update readme setup requirements

- src/common/storage.js
- src/components/common/passcode/passcode.modal.verify.js
- src/components/common/passcode/wrongPasscodeUtils.js
Fixes issue where java was failing on converting double to string.
1. Convert integers to strings before saving them to storage.
2. Check on return if the key exists, then convert to double or assume 0
3. When writing data, give value. This was the line that was failing.
> Fix double

- src/common/transaction/index.js
- src/common/transaction/rbtccoin.js
- src/pages/wallet/transfer.js
When trying to send a tx using a Token, an error occurred saying "Internal Error".
During the process of building the tx, we mix inside the code the use of "checksum vs lowercase". In this case, *I think* it was an incompatibility between library checksums, but the real matter it is that we don't need it in order to operate with the network. Checksums are only needed for user, when interacting with addresses as a second factor of verification. 
As this fix doesn't actually change that verification (it is made in another level), we send lowercase address as the final address in the transaction.
> fix: fix token estimation of fees and transfer

- src/common/storage.js
**Issue**
When the users resets/change phone, all data is migrated to the new phone, when for security reasons it shouldn't. The private data should 'live' only on the scope of the current device. 
**Tech description**
rWallet uses lib [rn-secure-storage](https://github.com/talut/rn-secure-storage#keychainaccessible-enum) for saving data in the device, from their docs they have some ways to set how to save data.
To fix it lets change to:
- **`WHEN_UNLOCKED_THIS_DEVICE_ONLY`**: The data in the keychain item can be accessed only while the device is unlocked by the user. Items with this attribute do not migrate to a new device.
**What do we store?**
- Passcode
- Mnemonic phrase
- Private key
- User password
**How to test it**
- Install the app in a new device with apple account set. 
- …
> chore: set storage not 'migrable'

- src/common/translations/pt-BR.json
* **Other information**:
* **SCREENSHOTS**:
> Changes PT-BR
